<a href="https://colab.research.google.com/github/Pranavkharat-S/ML25/blob/main/Ass_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [79]:
import numpy as np

In [80]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [81]:
np.array(my_list)

array([1, 2, 3])

In [82]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [83]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [86]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [87]:
np.ones(3)

array([1., 1., 1.])

In [88]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [89]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [90]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [91]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [92]:
np.random.rand(2)

array([0.81091616, 0.2134512 ])

In [93]:
np.random.rand(5,5)

array([[0.94216346, 0.05507539, 0.13129873, 0.79310708, 0.9107977 ],
       [0.77626548, 0.05973903, 0.18088031, 0.81618845, 0.25723701],
       [0.17722526, 0.05076508, 0.41080188, 0.4262361 , 0.87023346],
       [0.20633162, 0.21545796, 0.37998661, 0.89987064, 0.2489875 ],
       [0.97206258, 0.64600024, 0.99885679, 0.44450433, 0.87873908]])

In [94]:
np.random.randn(2)

array([-1.01310693, -0.40724604])

In [95]:
np.random.randn(5,5)

array([[ 0.85117225, -0.25043519, -0.79083984, -0.03091291,  0.56009038],
       [ 1.12302149, -2.12606944, -0.12889674,  0.47296412,  0.4912475 ],
       [ 1.41612503,  0.60505204, -0.99620538, -1.09055766,  0.35149413],
       [ 0.51886805, -0.84394993, -0.66876192,  1.57711192,  2.00376984],
       [ 0.20342272,  0.80331071,  1.19623514,  2.62780227, -0.39426639]])

In [96]:
np.random.randint(1,100)

5

In [97]:
np.random.randint(1,100,10)

array([92,  5, 89, 66, 64, 71, 70, 45, 30, 25])

In [98]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [99]:
ranarr

array([20,  2, 24, 16, 19, 46,  1, 18, 21, 28])

In [100]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [101]:
ranarr

array([20,  2, 24, 16, 19, 46,  1, 18, 21, 28])

In [102]:
ranarr.max()

np.int64(46)

In [103]:
ranarr.argmax()

np.int64(5)

In [104]:
ranarr.min()

np.int64(1)

In [105]:
ranarr.argmin()

np.int64(6)

In [106]:
arr.shape

(25,)

In [107]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [108]:
arr.reshape(1,25).shape

(1, 25)

In [109]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [110]:
arr.reshape(25,1).shape

(25, 1)

In [111]:
arr.dtype

dtype('int64')